import { StyleSheet } from "react-native";

export const COLORS = {
  primary: "#3b5741",
  Secondary: "#69876f",
  InActive: "grey",
  TextInputColor: "#1111",
  Notification: "#fff",
  white: "#FFF",
  dark: "#000",
  light: "#f6f6f6",
  subComment: "#fafafa",
  grey: "#A9A9A9",
  blue: "#5f82e6",
  red: "red",
  tranparent: "rgba(0,0,0,0)",
};

export const styles = StyleSheet.create({
  SearchBackgroundStyle: {
    //marginTop: 2,
    margin: 10,
    backgroundColor: "white",
    height: 50,
    borderWidth: 0,
    borderRadius: 5,
    //marginHorizontal: 3,
    flexDirection: "row",
    shadowRadius: 30,
    //borderColor: COLORS.InActive,
    elevation: 10,
    shadowOpacity: 0.2,
    shadowColor: "#000",
    shadowRadius: 3,
    shadowOffset: {
      height: 1,
    },
  },
  SearchInputStyle: {
    fontSize: 18,
    flex: 1,
  },
  SearchIconStyle: {
    fontSize: 35,
    alignSelf: "center",
    marginHorizontal: 15,
  },
  button: {
    width: 200,
    marginTop: 20,
    backgroundColor: COLORS.Secondary,
    padding: 15,
    borderRadius: 10,
  },
  btnText: {
    color: "white",
    fontSize: 20,
    justifyContent: "center",
    textAlign: "center",
  },
  textInputs: {
    borderStartWidth: 2,
    borderEndWidth: 3,
    borderTopWidth: 1,
    borderLeftWidth: 2,
    borderRightWidth: 3,
    borderBottomWidth: 4,
    borderColor: COLORS.Secondary,
    paddingVertical: 5,
    color: "black",
    paddingLeft: 10,
    height: 40,
    width: "100%",
    borderRadius: 7,
    marginVertical: 5,
  },
  textArea: {
    borderStartWidth: 2,
    borderEndWidth: 3,
    borderTopWidth: 1,
    borderLeftWidth: 2,
    borderRightWidth: 3,
    borderBottomWidth: 4,
    borderColor: COLORS.Secondary,
    color: "black",
    paddingVertical: -10,
    paddingHorizontal: 10,
    height: 60,
    width: "100%",
    borderRadius: 7,
    marginVertical: 5,
  },

  finalReviewContainer: {
    flex: 1,
    margin: 0,
    width: "100%",
    alignItems: "center",
    backgroundColor: COLORS.Secondary,
  },
  finalReviewText: {
    fontSize: 18,
    color: "white",
    width: "90%",
    textAlign: "center",
    borderStyle: "dotted",
    borderWidth: 1,
    borderColor: "white",
    paddingVertical: 5,
    marginVertical: 5,
    borderRadius: 5,
  },
  finalReviewButton: {
    backgroundColor: COLORS.primary,
    width: 100,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 7,
    margin: 7,
    fontWeight: "bold",
  },
  validationError: {
    color: "#FFa9a9",
    fontSize: 12,
    display: "flex",
    width: "100%",
    textAlign: "right",
    paddingRight: 7,
  },

  /* NEW LISTINGS STUFF STARTS */

  container: {
    flex: 0,
    backgroundColor: "#fff",
    justifyContent: "flex-start",
    paddingHorizontal: 0,
    marginBottom: -23,
    marginTop: 20,
  },
  italic: {
    fontStyle: "italic",
    textAlign: "right",
  },
  btns: {
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.Secondary,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingBottom: 0,
    marginBottom: 0,
    margin: 0,
    paddingVertical: 0,
  },
  stepTitle: {
    textAlign: "center",
    color: COLORS.Secondary,
    fontWeight: "bold",
    fontSize: 18,
  },
  stepTitleSmall: {
    textAlign: "center",
    color: COLORS.Secondary,
    fontSize: 16,
    marginBottom: 10,
    marginTop: 35,
  },
  listingSlider: {
    width: "60%",
    height: 120,
    overflow: "hidden",
    alignItems: "center",
    borderRadius: 6,

    borderWidth: 2,
    borderStyle: "dotted",
    borderColor: "lightgray",
    backgroundColor: "white",
  },
});
